@token = Token {{login.response.body.token}}
@baseUrl = http://localhost:8000


# @name users
post {{baseUrl}}/users
Content-Type: application/json

{
    "username":"test1",
    "password":"test1",
    "email":"test1@gmail.com"
}

###

# @name login
post {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username":"test1",
    "password":"test1",
    "email":"test1@gmail.com"
}
###

# @name pizzas
get {{baseUrl}}/pizzas
Content-Type: application/json
Authorization: {{token}}