#######  GLOBAL  #######
# @name GlobalGET
GET http://localhost:8000

###
# @name Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "userName":"test-1",
    "password":"test-1"
}

###
# @name Loguot
POST http://localhost:8000/auth/logout
Content-Type: application/json

#######  LIST  #######
# @name DepartmentList
GET http://localhost:8000/departments/

###
# @name PersonnelList
GET http://localhost:8000/personnels/

#######  READ  #######
# @name DepartmentRead
GET http://localhost:8000/departments/68be0dc941da88a3af164298

###
# @name PersonnelRead
GET http://localhost:8000/personnels/68c1eb886ba4f112404660f5

#######  CREATE  #######
# @name DepartmentCreate
POST http://localhost:8000/departments
Content-Type: application/json

{
    "name": "FS-19"
}

###
# @name PersonnelCreate
GET http://localhost:8000/personnels/
Content-Type: application/json

{
    "departmentId": "68c05d59e15655549e617ff5",
    "userName": "test-1",
    "password": "test-1",
    "firstName": "test-1-f",
    "lastName": "test-1-l",
    "phone": "905551234567",
    "email": "test-1@test.com",
    "title": "test-1-title",
    "salary": 2000,
    "description": "test-1-desc"
}

#######  UPDATE  #######
# @name DepartmentUpdate
PUT http://localhost:8000/departments/68be0dc941da88a3af164298
Content-Type: application/json

{
    "name": "FS-19"
}

#######  DELETE  #######
# @name DepartmentDelete
GET http://localhost:8000/departments/68be0dc941da88a3af164298