
################################
##########  VARIABLES  #########
################################
@baseUrl = http://localhost:8000
@simpleToken = Token {{Login.response.body.token}}
@accesToken = Bearer {{Login.response.body.bearer.access}}
@refreshToken = Bearer {{Login.response.body.bearer.refresh}}

################################
###########  GLOBAL  ###########
################################
# @name GlobalGET
GET {{baseUrl}}
###
# @name Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "userName":"",
    "password":"",
    "email": ""
}

###
# @name Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

###
# @name RefreshToken
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
"refresh": ""
}

################################
############  LIST  ############
################################

# @name List_Users
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: {{simpleToken}}

###


################################
############  READ  ############
################################

# @name Read_User
GET {{baseUrl}}/users/68c9964cf3c093b2532da0c4

###

################################
###########  CREATE  ###########
################################

# @name Create_User
POST http://localhost:8000/users
Content-Type: application/json

{
    "userName":"",
    "password":"",
    "email":""
}

###

################################
###########  UPDATE  ###########
################################


# @name Update_User
PUT {{baseUrl}}/users/
Content-Type: application/json

{
    "name": ""
}

###

################################
###########  DELETE  ###########
################################

# @name Delete_User
DELETE  {{baseUrl}}/users/

###
