
################################
##########  VARIABLES  #########
################################
@baseUrl = http://localhost:8000
@accesToken = Bearer {{Login.response.body.bearer.access}}
@refreshToken = {{Login.response.body.bearer.refresh}}

################################
###########  GLOBAL  ###########
################################
# @name GlobalGET
GET {{baseUrl}}
###
# @name Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"aA?123456"
}

###
# @name Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

###
# @name RefreshToken
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
"refresh": "{{refreshToken}}"
}

################################
############  LIST  ############
################################

# @name LIST_Users
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name LIST_Tokens
GET {{baseUrl}}/tokens
Content-Type: application/json
Authorization: {{accesToken}}

{
    "startDate": "2025-10-10",
    "endDate": "2025-10-15"
}

###
# @name LIST_Brands
GET {{baseUrl}}/brands
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name LIST_categories
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name LIST_firms
GET {{baseUrl}}/firms
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name LIST_products
GET {{baseUrl}}/products
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name LIST_purchases
GET {{baseUrl}}/purchases
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name LIST_sales
GET {{baseUrl}}/sales
Content-Type: application/json
Authorization: {{accesToken}}

################################
############  READ  ############
################################

# @name READ_Users
GET {{baseUrl}}/users/65343222b67e9681f937f001
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name READ_Token
GET {{baseUrl}}/tokens/68d4341cc99a59c2c23cf4dd
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name READ_Brands
GET {{baseUrl}}/brands/65343222b67e9681f937f104
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name READ_Categories
GET {{baseUrl}}/categories/65343222b67e9681f937f201
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name READ_Firms
GET {{baseUrl}}/firms/65343222b67e9681f937f302
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name READ_Products
GET {{baseUrl}}/products/65343222b67e9681f937f421
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name READ_Purchases
GET {{baseUrl}}/purchases/65343222b67e9681f937f513
Content-Type: application/json
Authorization: {{accesToken}}

###
# @name READ_Sales
GET {{baseUrl}}/sales/65343222b67e9681f937f614
Content-Type: application/json
Authorization: {{accesToken}}

################################
###########  CREATE  ###########
################################

# @name Create_User
POST {{baseUrl}}/users
Content-Type: application/json
# Authorization: {{accesToken}}

{
    "username":"test3",
    "password": "aA*12345",
    "email":"test3@gmail.com",
    "firstName":"test3",
    "lastName":"test3"
}

###
# @name Create_Sales
POST {{baseUrl}}/sales
Content-Type: application/json
# Authorization: {{accesToken}}

{
    "username":"test1",
    "password": "aA*12345",
    "email":"test1@gmail.com",
    "firstName":"test1",
    "lastName":"test1"
}

################################
###########  UPDATE  ###########
################################


# @name Update_User
PUT {{baseUrl}}/users/
Content-Type: application/json

{
    "name": ""
}
###
# @name Update_Car
PUT {{baseUrl}}/cars/64c5ed12345a12345678901a
Content-Type: application/json
Authorization: {{accesToken}}

{
    "pricePerDay": 120
}

###

################################
###########  DELETE  ###########
################################

# @name DELETE
DELETE  {{baseUrl}}/nerden/neyi

###
